### ISSUE TITLE
prefix for .tap filename

### ISSUE THREAD

**Issue by miked-mellanox** [kinow/gtest-tap-listener#9]
Hi,
Could you please add:
* configurable prefix for filename generated by tap.h
* Location where to store .tap files?

The use-case is as following:

- we run gtest 2-3 time:
- w/ valgringd
- w/ code coverage
- just gtest

Every execution overrides .tap files created on previous step.

The proposal:

``` shell
% GTEST_TAP_FILENAME_PREFIX="gtest_vg_" valgrind gtest
% GTEST_TAP_FILENAME_PREFIX="gtest_codecov_" codecov gtest
% GTEST_TAP_DIR=/tmp/taps gtest
```

Thanks

**Comment by toch** [comment]
Hi @miked-mellanox,

It could be indeed useful. I'd make it an attribute of the [TapListener class](https://github.com/kinow/gtest-tap-listener/blob/master/src/tap.h#L171) rather than passing it as an environment variable that will need to recompile the test program.

FYI, the filename is provided [in the method TapListener::OnTestProgramEnd](https://github.com/kinow/gtest-tap-listener/blob/master/src/tap.h#L238).

**Comment by miked-mellanox** [comment]
Hi,
attribute will require to code filename and location logic into test code.
having it set from outside (env) is much more flexible and does not require test code changes.

**Comment by toch** [comment]
Do you mean, you would provide the environment to your test program?

**Comment by miked-mellanox** [comment]
env variables. gtest already accepts env variables as input parameters.

**Comment by toch** [comment]
True. Thanks for the clarification.

> attribute will require to code filename and location logic into test code.

well, just when you create the listener. but I guess, providing a way to capture the right env is a nice option.

**Comment by kinow** [comment]
I'll take a look again at this issue next month, and will try my hand at some C code again (write mainly Java and Python nowadays). However, should there is a pull request, it's even easier for me to merge it and learn while doing so.

@toch, you have helped lots of people here, and always reviews issue before I do, so I've added you to the project collaborators. You should be able to push to the repository if necessary. :-)

**Comment by toch** [comment]
@kinow sorry for not having answered you. thanks for adding me as contributor :blush: 

@miked-mellanox does 07a6c8e correspond to what you had in mind?

**Comment by kinow** [comment]
Had a look at 07a6c8e, and it looks neat, kudos @toch! Let's wait a few more days for @miked-mellanox to comment here, and then mark it as resolved :-)

**Comment by miked-mellanox** [comment]
:+1: 
thanks a lot

**Comment by kinow** [comment]
That was super fast @miked-mellanox. Closing the issue.
